name: CI

on:
  push:
    branches: ["feat/*", "fix/*", "chore/*", "main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm lint || true # placeholder until scripts exist
      - name: Typecheck
        run: pnpm typecheck || true
      - name: Test
        run: pnpm test || true
      - name: Build
        run: pnpm build || true

